services:
    _defaults:
        public: true
        autowire: true

    # SERVICES
    HBM\DatagridBundle\Service\DatagridHelper:
        arguments:
            $config: "%hbm.datagrid%"

    hbm.helper.datagrid:
        alias: HBM\DatagridBundle\Service\DatagridHelper

    HBM\DatagridBundle\Service\QueryEncoder:
        arguments:
            $mode: "%hbm.datagrid.query_encode_mode%"

    hbm.helper.datagrid.query_encoder:
        alias: HBM\DatagridBundle\Service\QueryEncoder

    # TWIG
    HBM\DatagridBundle\Twig\Extension\:
        resource: '../../Twig/Extension/*'
        tags:
            - { name: twig.extension }
