services:
    _defaults:
        public: true
        autowire: true

    # SERVICES
    HBM\DatagridBundle\Service\DatagridHelper:
        arguments:
            $config: "%hbm.datagrid%"

    hbm.helper.datagrid:
        alias: HBM\DatagridBundle\Service\DatagridHelper

    HBM\DatagridBundle\Service\QueryEncoder: ~

    hbm.helper.datagrid.query_encoder:
        alias: HBM\DatagridBundle\Service\QueryEncoder

    # TWIG
    HBM\DatagridBundle\Twig\Extension\:
        resource: '../src/Twig/Extension/*'
        tags:
            - { name: twig.extension }

    HBM\DatagridBundle\Twig\Runtime\:
        resource: '../src/Twig/Runtime/*'
        tags:
            - { name: twig.runtime }
